server:
  port: 8080

spring:
  application:
    name: BarclaysTestService
  datasource:
    url: jdbc:h2:file:./barclays-test-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
jwt:
  secret-key: this-is-a-really-really-secret-key-honest!
  expiry-seconds: 600


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method


