CREATE SEQUENCE IF NOT EXISTS userdetail_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS address_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS bankaccount_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS transaction_seq START WITH 1 INCREMENT BY 1;
